# Generated by Django 3.2.20 on 2023-07-03 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReplyComment',
        ),
    ]
